[[established_account]]
vp = "vp_user"
threshold = 2
public_keys = ["tpknam1qq9ervwysmaldyeqgrsdx7y3mt5f2skuj9azvw04fgnxdyfd97sxxqmh55a", "tpknam1qq9ervwysmaldyeqgrsdx7y3mt5f2skuj9azvw04fgnxdyfd97sxxqmh55a"]